name: Test workflow that runs on all branches except main.
on: 
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - 'main'
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt install cowsay
      - name: Main script
        run: |
          cowsay "Only on branches other than main."